# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\soc_proj\proj_0_main_proj\HPS_Quartus_13.1_Python2.7\PyQT_main_window\soc_gui.ui'
#
# Created: Thu Sep 15 14:25:28 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1027, 735)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.graphicsView_preview = QtGui.QGraphicsView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphicsView_preview.sizePolicy().hasHeightForWidth())
        self.graphicsView_preview.setSizePolicy(sizePolicy)
        self.graphicsView_preview.setMinimumSize(QtCore.QSize(201, 50))
        self.graphicsView_preview.setMaximumSize(QtCore.QSize(16777215, 100))
        self.graphicsView_preview.setObjectName(_fromUtf8("graphicsView_preview"))
        self.graphicsView_wave = QtGui.QGraphicsView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.graphicsView_wave.sizePolicy().hasHeightForWidth())
        self.graphicsView_wave.setSizePolicy(sizePolicy)
        self.graphicsView_wave.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView_wave.setResizeAnchor(QtGui.QGraphicsView.NoAnchor)
        self.graphicsView_wave.setObjectName(_fromUtf8("graphicsView_wave"))
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1027, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_control = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_control.sizePolicy().hasHeightForWidth())
        self.dockWidget_control.setSizePolicy(sizePolicy)
        self.dockWidget_control.setFloating(False)
        self.dockWidget_control.setObjectName(_fromUtf8("dockWidget_control"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pushButton_ctrl_dock = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_ctrl_dock.setObjectName(_fromUtf8("pushButton_ctrl_dock"))
        self.verticalLayout_6.addWidget(self.pushButton_ctrl_dock)
        self.scrollArea_2 = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(425, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 423, 470))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.line = QtGui.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.comboBox_couple_mode = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_couple_mode.setObjectName(_fromUtf8("comboBox_couple_mode"))
        self.comboBox_couple_mode.addItem(_fromUtf8(""))
        self.comboBox_couple_mode.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox_couple_mode)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.comboBox_4)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.verticalLayout_4.addWidget(self.comboBox_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.lcdNumber_ofst_ch1 = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumber_ofst_ch1.setObjectName(_fromUtf8("lcdNumber_ofst_ch1"))
        self.verticalLayout_4.addWidget(self.lcdNumber_ofst_ch1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dial_ofst_ch1 = QtGui.QDial(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_ofst_ch1.sizePolicy().hasHeightForWidth())
        self.dial_ofst_ch1.setSizePolicy(sizePolicy)
        self.dial_ofst_ch1.setMinimumSize(QtCore.QSize(50, 50))
        self.dial_ofst_ch1.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_ofst_ch1.setMinimum(-120)
        self.dial_ofst_ch1.setMaximum(120)
        self.dial_ofst_ch1.setObjectName(_fromUtf8("dial_ofst_ch1"))
        self.horizontalLayout_2.addWidget(self.dial_ofst_ch1)
        self.toolButton_ofst_ch1 = QtGui.QToolButton(self.groupBox_3)
        self.toolButton_ofst_ch1.setText(_fromUtf8(""))
        self.toolButton_ofst_ch1.setObjectName(_fromUtf8("toolButton_ofst_ch1"))
        self.horizontalLayout_2.addWidget(self.toolButton_ofst_ch1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.pushButton_ofst_rst_ch1 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_ofst_rst_ch1.setObjectName(_fromUtf8("pushButton_ofst_rst_ch1"))
        self.verticalLayout_4.addWidget(self.pushButton_ofst_rst_ch1)
        self.lcdNumber_gain_ch1 = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumber_gain_ch1.setSmallDecimalPoint(False)
        self.lcdNumber_gain_ch1.setObjectName(_fromUtf8("lcdNumber_gain_ch1"))
        self.verticalLayout_4.addWidget(self.lcdNumber_gain_ch1)
        self.dial_gain_ch1 = QtGui.QDial(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_gain_ch1.sizePolicy().hasHeightForWidth())
        self.dial_gain_ch1.setSizePolicy(sizePolicy)
        self.dial_gain_ch1.setMinimumSize(QtCore.QSize(100, 100))
        self.dial_gain_ch1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.dial_gain_ch1.setWrapping(False)
        self.dial_gain_ch1.setNotchesVisible(False)
        self.dial_gain_ch1.setObjectName(_fromUtf8("dial_gain_ch1"))
        self.verticalLayout_4.addWidget(self.dial_gain_ch1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.line_2 = QtGui.QFrame(self.groupBox_4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_5.addWidget(self.label_10)
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.comboBox_6)
        self.pushButton_preview_view = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_preview_view.setCheckable(True)
        self.pushButton_preview_view.setChecked(True)
        self.pushButton_preview_view.setObjectName(_fromUtf8("pushButton_preview_view"))
        self.verticalLayout_5.addWidget(self.pushButton_preview_view)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.lcdNumber_time_ofst = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_time_ofst.setObjectName(_fromUtf8("lcdNumber_time_ofst"))
        self.verticalLayout_5.addWidget(self.lcdNumber_time_ofst)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.dial_ofst_time = QtGui.QDial(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_ofst_time.sizePolicy().hasHeightForWidth())
        self.dial_ofst_time.setSizePolicy(sizePolicy)
        self.dial_ofst_time.setMinimumSize(QtCore.QSize(50, 50))
        self.dial_ofst_time.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_ofst_time.setMinimum(-120)
        self.dial_ofst_time.setMaximum(120)
        self.dial_ofst_time.setObjectName(_fromUtf8("dial_ofst_time"))
        self.horizontalLayout_5.addWidget(self.dial_ofst_time)
        self.toolButton_ofst_time = QtGui.QToolButton(self.groupBox_4)
        self.toolButton_ofst_time.setText(_fromUtf8(""))
        self.toolButton_ofst_time.setObjectName(_fromUtf8("toolButton_ofst_time"))
        self.horizontalLayout_5.addWidget(self.toolButton_ofst_time)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.pushButton_ofst_rst_time = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_ofst_rst_time.setObjectName(_fromUtf8("pushButton_ofst_rst_time"))
        self.verticalLayout_5.addWidget(self.pushButton_ofst_rst_time)
        self.lcdNumber_time_scale = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_time_scale.setObjectName(_fromUtf8("lcdNumber_time_scale"))
        self.verticalLayout_5.addWidget(self.lcdNumber_time_scale)
        self.dial_time_scale = QtGui.QDial(self.groupBox_4)
        self.dial_time_scale.setMinimumSize(QtCore.QSize(100, 100))
        self.dial_time_scale.setMaximumSize(QtCore.QSize(16777215, 100))
        self.dial_time_scale.setObjectName(_fromUtf8("dial_time_scale"))
        self.verticalLayout_5.addWidget(self.dial_time_scale)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox_trigger_mode = QtGui.QComboBox(self.groupBox)
        self.comboBox_trigger_mode.setObjectName(_fromUtf8("comboBox_trigger_mode"))
        self.comboBox_trigger_mode.addItem(_fromUtf8(""))
        self.comboBox_trigger_mode.addItem(_fromUtf8(""))
        self.comboBox_trigger_mode.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_trigger_mode)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.spinBox_trigger_level = QtGui.QSpinBox(self.groupBox)
        self.spinBox_trigger_level.setMaximum(255)
        self.spinBox_trigger_level.setProperty("value", 127)
        self.spinBox_trigger_level.setObjectName(_fromUtf8("spinBox_trigger_level"))
        self.verticalLayout_2.addWidget(self.spinBox_trigger_level)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dial_time_ofst_2 = QtGui.QDial(self.groupBox)
        self.dial_time_ofst_2.setMinimumSize(QtCore.QSize(50, 50))
        self.dial_time_ofst_2.setMaximumSize(QtCore.QSize(50, 50))
        self.dial_time_ofst_2.setMinimum(-120)
        self.dial_time_ofst_2.setMaximum(120)
        self.dial_time_ofst_2.setObjectName(_fromUtf8("dial_time_ofst_2"))
        self.horizontalLayout_3.addWidget(self.dial_time_ofst_2)
        self.toolButton_2 = QtGui.QToolButton(self.groupBox)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_10.addWidget(self.label_3)
        self.spinBox_draw_brightness = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_draw_brightness.setMinimum(10)
        self.spinBox_draw_brightness.setMaximum(255)
        self.spinBox_draw_brightness.setProperty("value", 200)
        self.spinBox_draw_brightness.setObjectName(_fromUtf8("spinBox_draw_brightness"))
        self.verticalLayout_10.addWidget(self.spinBox_draw_brightness)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_10.addWidget(self.label_4)
        self.spinBox_line_width = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_line_width.setMinimum(1)
        self.spinBox_line_width.setMaximum(6)
        self.spinBox_line_width.setObjectName(_fromUtf8("spinBox_line_width"))
        self.verticalLayout_10.addWidget(self.spinBox_line_width)
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_10.addWidget(self.label_11)
        self.comboBox = QtGui.QComboBox(self.groupBox_6)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayout_10.addWidget(self.comboBox)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_10.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.groupBox_6)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.dockWidget_control.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_control)
        self.dockWidget_measure = QtGui.QDockWidget(MainWindow)
        self.dockWidget_measure.setObjectName(_fromUtf8("dockWidget_measure"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.pushButton_meas_dock = QtGui.QPushButton(self.dockWidgetContents_4)
        self.pushButton_meas_dock.setObjectName(_fromUtf8("pushButton_meas_dock"))
        self.verticalLayout_7.addWidget(self.pushButton_meas_dock)
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents_4)
        self.scrollArea.setMinimumSize(QtCore.QSize(135, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 133, 470))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_hor_meas_1 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_hor_meas_1.setObjectName(_fromUtf8("comboBox_hor_meas_1"))
        self.comboBox_hor_meas_1.addItem(_fromUtf8(""))
        self.comboBox_hor_meas_1.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_hor_meas_1)
        self.lcdNumber_hor_meas_1 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_hor_meas_1.setObjectName(_fromUtf8("lcdNumber_hor_meas_1"))
        self.verticalLayout_3.addWidget(self.lcdNumber_hor_meas_1)
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.comboBox_hor_meas_2 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_hor_meas_2.setObjectName(_fromUtf8("comboBox_hor_meas_2"))
        self.comboBox_hor_meas_2.addItem(_fromUtf8(""))
        self.comboBox_hor_meas_2.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_hor_meas_2)
        self.lcdNumber_hor_meas_2 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_hor_meas_2.setObjectName(_fromUtf8("lcdNumber_hor_meas_2"))
        self.verticalLayout_3.addWidget(self.lcdNumber_hor_meas_2)
        self.comboBox_hor_meas_3 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_hor_meas_3.setObjectName(_fromUtf8("comboBox_hor_meas_3"))
        self.comboBox_hor_meas_3.addItem(_fromUtf8(""))
        self.comboBox_hor_meas_3.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox_hor_meas_3)
        self.line_4 = QtGui.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.lcdNumber_hor_meas_3 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_hor_meas_3.setObjectName(_fromUtf8("lcdNumber_hor_meas_3"))
        self.verticalLayout_3.addWidget(self.lcdNumber_hor_meas_3)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.comboBox_ver_mes_1 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_ver_mes_1.setObjectName(_fromUtf8("comboBox_ver_mes_1"))
        self.comboBox_ver_mes_1.addItem(_fromUtf8(""))
        self.comboBox_ver_mes_1.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.comboBox_ver_mes_1)
        self.lcdNumber_ver_mes_1 = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_ver_mes_1.setObjectName(_fromUtf8("lcdNumber_ver_mes_1"))
        self.verticalLayout_8.addWidget(self.lcdNumber_ver_mes_1)
        self.line_6 = QtGui.QFrame(self.groupBox_5)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_8.addWidget(self.line_6)
        self.comboBox_ver_mes_2 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_ver_mes_2.setObjectName(_fromUtf8("comboBox_ver_mes_2"))
        self.comboBox_ver_mes_2.addItem(_fromUtf8(""))
        self.comboBox_ver_mes_2.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.comboBox_ver_mes_2)
        self.lcdNumber_ver_mes_2 = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_ver_mes_2.setObjectName(_fromUtf8("lcdNumber_ver_mes_2"))
        self.verticalLayout_8.addWidget(self.lcdNumber_ver_mes_2)
        self.line_7 = QtGui.QFrame(self.groupBox_5)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_8.addWidget(self.line_7)
        self.comboBox_ver_mes_3 = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_ver_mes_3.setObjectName(_fromUtf8("comboBox_ver_mes_3"))
        self.comboBox_ver_mes_3.addItem(_fromUtf8(""))
        self.comboBox_ver_mes_3.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.comboBox_ver_mes_3)
        self.lcdNumber_ver_mes_3 = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_ver_mes_3.setObjectName(_fromUtf8("lcdNumber_ver_mes_3"))
        self.verticalLayout_8.addWidget(self.lcdNumber_ver_mes_3)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.dockWidget_measure.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_measure)
        self.dockWidget_quick_set = QtGui.QDockWidget(MainWindow)
        self.dockWidget_quick_set.setObjectName(_fromUtf8("dockWidget_quick_set"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_4 = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.scrollArea_3 = QtGui.QScrollArea(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 826, 88))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spinBox_ch1_vertical = QtGui.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_ch1_vertical.setMinimum(0)
        self.spinBox_ch1_vertical.setMaximum(511)
        self.spinBox_ch1_vertical.setProperty("value", 127)
        self.spinBox_ch1_vertical.setObjectName(_fromUtf8("spinBox_ch1_vertical"))
        self.gridLayout_2.addWidget(self.spinBox_ch1_vertical, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_2.addWidget(self.pushButton_10, 1, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.line_10 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_6.addWidget(self.line_10)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_15 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_5.addWidget(self.pushButton_15, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_5.addWidget(self.spinBox_5, 1, 0, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_5.addWidget(self.pushButton_14, 0, 2, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_5.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_5.addWidget(self.pushButton_16, 1, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_5)
        self.line_9 = QtGui.QFrame(self.scrollAreaWidgetContents_3)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout_6.addWidget(self.line_9)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.spinBox_4 = QtGui.QSpinBox(self.scrollAreaWidgetContents_3)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_3.addWidget(self.spinBox_4, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_3.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_3.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.addWidget(self.scrollArea_3)
        self.label_12 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_4.addWidget(self.label_12)
        self.dockWidget_quick_set.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_quick_set)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionFull_Screen = QtGui.QAction(MainWindow)
        self.actionFull_Screen.setObjectName(_fromUtf8("actionFull_Screen"))
        self.actionNormal_Window = QtGui.QAction(MainWindow)
        self.actionNormal_Window.setObjectName(_fromUtf8("actionNormal_Window"))
        self.actionDock_Control = QtGui.QAction(MainWindow)
        self.actionDock_Control.setCheckable(True)
        self.actionDock_Control.setObjectName(_fromUtf8("actionDock_Control"))
        self.actionDock_Measure = QtGui.QAction(MainWindow)
        self.actionDock_Measure.setCheckable(True)
        self.actionDock_Measure.setObjectName(_fromUtf8("actionDock_Measure"))
        self.actionDock_Quick_Set = QtGui.QAction(MainWindow)
        self.actionDock_Quick_Set.setCheckable(True)
        self.actionDock_Quick_Set.setObjectName(_fromUtf8("actionDock_Quick_Set"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionSettings)
        self.menuView.addAction(self.actionNormal_Window)
        self.menuView.addAction(self.actionFull_Screen)
        self.menuView.addSeparator()
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDock_Control)
        self.menuView.addAction(self.actionDock_Measure)
        self.menuView.addAction(self.actionDock_Quick_Set)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFull_Screen)
        self.toolBar.addAction(self.actionNormal_Window)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDock_Control)
        self.toolBar.addAction(self.actionDock_Measure)
        self.toolBar.addAction(self.actionDock_Quick_Set)
        self.label_5.setBuddy(self.comboBox_couple_mode)
        self.label_8.setBuddy(self.comboBox_4)
        self.label_9.setBuddy(self.comboBox_5)
        self.label_10.setBuddy(self.comboBox_6)
        self.label.setBuddy(self.comboBox_trigger_mode)
        self.label_2.setBuddy(self.spinBox_trigger_level)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.dial_gain_ch1, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_gain_ch1.display)
        QtCore.QObject.connect(self.actionFull_Screen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.showFullScreen)
        QtCore.QObject.connect(self.actionNormal_Window, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.showNormal)
        QtCore.QObject.connect(self.actionDock_Control, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidget_control.setVisible)
        QtCore.QObject.connect(self.dockWidget_control, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDock_Control.setChecked)
        QtCore.QObject.connect(self.actionDock_Measure, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidget_measure.setVisible)
        QtCore.QObject.connect(self.dockWidget_measure, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDock_Measure.setChecked)
        QtCore.QObject.connect(self.pushButton_preview_view, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.graphicsView_preview.setVisible)
        QtCore.QObject.connect(self.actionDock_Quick_Set, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.dockWidget_quick_set.setVisible)
        QtCore.QObject.connect(self.dockWidget_quick_set, QtCore.SIGNAL(_fromUtf8("visibilityChanged(bool)")), self.actionDock_Quick_Set.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_trigger_mode, self.spinBox_trigger_level)
        MainWindow.setTabOrder(self.spinBox_trigger_level, self.graphicsView_wave)
        MainWindow.setTabOrder(self.graphicsView_wave, self.graphicsView_preview)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Oscilloscope - Nanchang University", None))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.graphicsView_wave.setToolTip(_translate("MainWindow", "<html><head/><body><p>Waveform Display</p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.dockWidget_control.setToolTip(_translate("MainWindow", "<html><head/><body><p>Control Dock Window</p></body></html>", None))
        self.dockWidget_control.setWindowTitle(_translate("MainWindow", "Control", None))
        self.pushButton_ctrl_dock.setText(_translate("MainWindow", "Dock", None))
        self.groupBox_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>CH1 Settings</p></body></html>", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Channel 1", None))
        self.label_6.setText(_translate("MainWindow", "Vertical", None))
        self.label_5.setText(_translate("MainWindow", "Couple Mode", None))
        self.comboBox_couple_mode.setItemText(0, _translate("MainWindow", "DC", None))
        self.comboBox_couple_mode.setItemText(1, _translate("MainWindow", "AC", None))
        self.label_8.setText(_translate("MainWindow", "Probe", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "X1", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "X10", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.dial_ofst_ch1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position</p></body></html>", None))
        self.pushButton_ofst_rst_ch1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position Reset</p></body></html>", None))
        self.pushButton_ofst_rst_ch1.setText(_translate("MainWindow", "Offset Reset", None))
        self.groupBox_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Time Base Settings</p></body></html>", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Time Base", None))
        self.label_7.setText(_translate("MainWindow", "Horizontal", None))
        self.label_10.setText(_translate("MainWindow", "Dimension Mode", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "X-T", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Roll", None))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "X-Y", None))
        self.pushButton_preview_view.setText(_translate("MainWindow", "Preview", None))
        self.dial_ofst_time.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position</p></body></html>", None))
        self.pushButton_ofst_rst_time.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position Reset</p></body></html>", None))
        self.pushButton_ofst_rst_time.setText(_translate("MainWindow", "Offset Reset", None))
        self.groupBox.setTitle(_translate("MainWindow", "Trigger", None))
        self.label.setText(_translate("MainWindow", "Mode", None))
        self.comboBox_trigger_mode.setItemText(0, _translate("MainWindow", "Normal", None))
        self.comboBox_trigger_mode.setItemText(1, _translate("MainWindow", "Auto", None))
        self.comboBox_trigger_mode.setItemText(2, _translate("MainWindow", "Single", None))
        self.label_2.setText(_translate("MainWindow", "Level", None))
        self.dial_time_ofst_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Offset Position</p></body></html>", None))
        self.toolButton_2.setText(_translate("MainWindow", "½", None))
        self.pushButton.setText(_translate("MainWindow", "Set Zero", None))
        self.pushButton_2.setText(_translate("MainWindow", "Auto", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Display", None))
        self.label_3.setText(_translate("MainWindow", "Brightness", None))
        self.label_4.setText(_translate("MainWindow", "Drawing Width", None))
        self.label_11.setText(_translate("MainWindow", "Drawing Mode", None))
        self.pushButton_5.setText(_translate("MainWindow", "Reset", None))
        self.pushButton_3.setText(_translate("MainWindow", "Save", None))
        self.dockWidget_measure.setToolTip(_translate("MainWindow", "<html><head/><body><p>Measure Dock Window</p></body></html>", None))
        self.dockWidget_measure.setWindowTitle(_translate("MainWindow", "Measure", None))
        self.pushButton_meas_dock.setText(_translate("MainWindow", "Dock", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Horizontal", None))
        self.comboBox_hor_meas_1.setItemText(0, _translate("MainWindow", "Period", None))
        self.comboBox_hor_meas_1.setItemText(1, _translate("MainWindow", "Frequency", None))
        self.comboBox_hor_meas_2.setItemText(0, _translate("MainWindow", "Period", None))
        self.comboBox_hor_meas_2.setItemText(1, _translate("MainWindow", "Frequency", None))
        self.comboBox_hor_meas_3.setItemText(0, _translate("MainWindow", "Period", None))
        self.comboBox_hor_meas_3.setItemText(1, _translate("MainWindow", "Frequency", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Vertical", None))
        self.comboBox_ver_mes_1.setItemText(0, _translate("MainWindow", "Vp-p", None))
        self.comboBox_ver_mes_1.setItemText(1, _translate("MainWindow", "Vavg", None))
        self.comboBox_ver_mes_2.setItemText(0, _translate("MainWindow", "Vp-p", None))
        self.comboBox_ver_mes_2.setItemText(1, _translate("MainWindow", "Vavg", None))
        self.comboBox_ver_mes_3.setItemText(0, _translate("MainWindow", "Vp-p", None))
        self.comboBox_ver_mes_3.setItemText(1, _translate("MainWindow", "Vavg", None))
        self.dockWidget_quick_set.setToolTip(_translate("MainWindow", "<html><head/><body><p>Quick Set Dock Window</p></body></html>", None))
        self.dockWidget_quick_set.setWindowTitle(_translate("MainWindow", "Quick Set", None))
        self.pushButton_4.setText(_translate("MainWindow", "Dock", None))
        self.label_13.setText(_translate("MainWindow", "CH1 Vertical", None))
        self.pushButton_7.setText(_translate("MainWindow", "mV/Div", None))
        self.pushButton_10.setText(_translate("MainWindow", "V/Div", None))
        self.pushButton_15.setText(_translate("MainWindow", "ns/Div", None))
        self.label_15.setText(_translate("MainWindow", "Horizontal", None))
        self.pushButton_14.setText(_translate("MainWindow", "us/Div", None))
        self.pushButton_9.setText(_translate("MainWindow", "ms/Div", None))
        self.pushButton_16.setText(_translate("MainWindow", "s/Div", None))
        self.label_14.setText(_translate("MainWindow", "Trigger", None))
        self.pushButton_8.setText(_translate("MainWindow", "V", None))
        self.pushButton_11.setText(_translate("MainWindow", "mV", None))
        self.label_12.setToolTip(_translate("MainWindow", "Nanchang University ( NCU )", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body>\n"
"\n"
"\n"
"<img src = \"ncu.png\"/>\n"
"\n"
"\n"
"</body></html>", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen", None))
        self.actionFull_Screen.setToolTip(_translate("MainWindow", "Full Screen", None))
        self.actionNormal_Window.setText(_translate("MainWindow", "Normal Window", None))
        self.actionDock_Control.setText(_translate("MainWindow", "Dock Control", None))
        self.actionDock_Control.setToolTip(_translate("MainWindow", "Dock Control", None))
        self.actionDock_Measure.setText(_translate("MainWindow", "Dock Measure", None))
        self.actionDock_Quick_Set.setText(_translate("MainWindow", "Dock Quick Set", None))

